export const ORG_APPLICATION_STATUS = {
  DEFAULT: -1,
  PENDING: 0,
  APPROVED: 1,
  REJECTED: 2,
};

export const USER_ORGANIZATION_STATUS = {
  DEFAULT: -1,
  PENDING: 0,
  APPROVED: 1,
  REJECTED: 2,
};

export const EXPLORE_LOAD_TYPES = {
  INITIAL: 'INITIAL',
  SEARCH: 'SEARCH',
  FILTERED: 'FILTERED',
  TERM: 'TERM',
  DATETIME: 'DATETIME',
  STATUS: 'STATUS',
  ALL: 'ALL',
};

export const TEMPLATES_LOAD_TYPES = {
  INITIAL: 'INITIAL',
  SEARCH: 'SEARCH',
};

export const CACHE_KEY_NAMES = {
  ORGANIZATION: 'ORGANIZATION',
  MY_ORGANIZATION: 'MY_ORGANIZATION',
};

export const EVENT_STATUS = {
  ONGOING: 0,
  UPCOMING: 1,
  COMPLETED: 2,
};
